services:
  wx-filehelper-api:
    image: sxkiss/wx-filehelper-api:latest
    pull_policy: always
    ports:
      - "8070:8000"
    environment:
      PLUGINS_DIR: "/app/plugins"
    volumes:
      - "./data:/data"
    working_dir: "/data"
    restart: unless-stopped
